### ISSUE TITLE
I'm having the same issues as many other people, but their issues are being closed and it's assumed they didn't set the plugin up correctly. 

### ISSUE THREAD

**Issue by amydunc** [NuVotifier/NuVotifier#258]
The plugin worked, and then it stopped working. I've changed ports, I've contacted the host about a firewall, I have a dedicated IP, I've deleted the rsa, I've deleted the entire plugin and started from scratch. nothing makes this thing work. It is NOT a setup issue, I've spent days troubleshooting and conferring with other server owners and developers.

### Information

Config:

```
# The IP to listen to. Use 0.0.0.0 if you wish to listen to all interfaces on your server. (All IP addresses)
# This defaults to the IP you have configured your server to listen on, or 0.0.0.0 if you have not configured this.
host: 51.81.4.156

# Port to listen for new votes on
port: 2792

# Setting this option to true will disable handling of Protocol v1 packets. While the old protocol is not secure, this
# option is currently not recommended as most voting sites only support the old protocol at present. However, if you are
# using NuVotifier's proxy forwarding mechanism, enabling this option will increase your server's security.
disable-v1-protocol: false

# All tokens, labeled by the serviceName of each server list.
tokens:
  # Default token for all server lists, if another isn't supplied.
  default: [censored only because I don't wish to post this on github]

# Configuration section for all vote forwarding to NuVotifier
forwarding:
  # Sets whether to set up a remote method for fowarding. Supported methods:
  # - none - Does not set up a forwarding method.
  # - pluginMessaging - Sets up plugin messaging
  method: none
  pluginMessaging:
    channel: nuvotifier:votes

```
```
Console:
15.06 12:08:07 [Server] INFO amy_d issued server command: /nvreload
15.06 12:08:07 [Server] INFO Loaded token for website: default
15.06 12:08:07 [Server] INFO Using epoll transport to accept votes.
15.06 12:08:07 [Server] INFO Method none selected for vote forwarding: Votes will not be received from a forwarder.
15.06 12:08:07 [Server] INFO Reload was successful.
15.06 12:08:07 [Server] ERROR Votifier was not able to bind to /51.81.4.156:2792
```

### Details

No matter the troubleshooting, nuvotifier will not bind. I've done everything to try and fix the issue and there is nothing wrong with the config. It was working perfectly and then one day the plugin just quit on me.

**Steps to reproduce**  
There are no steps to reproduce. Unless there are other plugins that cause this one to break, it was random.

**Expected behavior** 
I expected the plugin to work and to bind.
